### ISSUE TITLE
Word-break w .min-chat__content__message

### ISSUE THREAD

**Issue by efiku** [CodersCommunity/czatrepajr#19]
Witam.
Czytam sobie chat i czasami denerwują mnie te łamania słów ( to samo tyczy się linków).

 ![screenshot 2015-08-23 13 38 05](https://cloud.githubusercontent.com/assets/13868237/9428060/6dcb53ec-499c-11e5-846d-c9d3b2fb9b89.png)

Kod css:
```css
.min-chat__content__message {
 /* ... */
	word-break: break-all;
/* ... */
}
```

Moim zdaniem ten problem naprawić powinna chyba zmiana na :

```css
.min-chat__content__message {
 /* ... */
	word-break: break-word;
/* ... */
}
```

![dd](https://cloud.githubusercontent.com/assets/13868237/9428075/65c01984-499d-11e5-919e-1c465f662c7d.png)

Przeglądarka: Chrome
