### ISSUE TITLE
Informacja na chacie o użytkownikach ( przyszedł , wyszedł )

### ISSUE THREAD

**Issue by efiku** [CodersCommunity/czatrepajr#25]
Hmm @magic96  mówił coś o systemowych wiadomościach.
Może być , w ogóle systemowe wiadomości mogłyby być pogrubione.

TODO: 
- [x] stworzenie kodu html odpowiedzialnego za wyświetlanie powiadomień.
- [x] stworzenie odpowiednich klas w css
- [x] kod js

Propozycja opcji drugiej:

Kod ( wstrzykiwany zaraz po divie id="min-chat-content" )
```css
.min-chat__status__message{
    text-align: center;
    font-size: 10px;
    color: #000;
    /* tu jeszcze jakieś inne opcje */
}
.min-chat__status__message--hidden{
   display: none;
}
.min-chat__status__message--offline{
  background-color: #CA3F3F;
}

.min-chat__status__message--online{
  background-color: #97CA3F
}
```

Dla osoby która opuściła chat
![xd](https://cloud.githubusercontent.com/assets/13868237/9489831/27b370ca-4be4-11e5-9bfd-275a687205c0.png)

Dla tej co właśnie przyszła:
![ddx](https://cloud.githubusercontent.com/assets/13868237/9489852/45d36808-4be4-11e5-93e6-0dca7a20bf73.png)

Oczywiście ta wiadomość znika po 2s?

Done
